<?php

/**
 * templates\index.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

namespace TechDivision\Example\Servlets;

use TechDivision\Example\Utils\ContextKeys;

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <base href="<?php echo $this->getBaseUrl() ?>">
    <title>Example</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="components/require.css" rel="stylesheet">
    <link rel="shortcut icon" href="static/img/favicon.png">
    <style type="text/css">
        body {
            padding-top: 20px;
            padding-bottom: 40px;
        }

            /* Custom container */
        .container-narrow {
            margin: 0 auto;
            max-width: 700px;
        }
        .container-narrow > hr {
            margin: 30px 0;
        }

            /* Main marketing message and sign up button */
        .jumbotron {
            margin: 60px 0;
            text-align: center;
        }
        .jumbotron h1 {
            font-size: 72px;
            line-height: 1;
        }
        .jumbotron .btn {
            font-size: 21px;
            padding: 14px 24px;
        }

            /* Supporting marketing content */
        .marketing {
            margin: 60px 0;
        }
        .marketing p + h4 {
            margin-top: 28px;
        }
    </style>
</head>

<body>

<div class="container-narrow">

    <div class="masthead">
        <ul class="nav nav-pills pull-right">
            <li><a href="index/index">Home</a></li>
            <li><a href="login/index">Login</a></li>
            <li><a href="upload/index">Upload</a></li>
            <li><a href="websocket/index">WebSocket</a></li>
            <li><a href="basicAuthentication/index">Basic Authentication</a></li>
            <li class="active"><a href="digestAuthentication/index">Digest Authentication</a></li>
        </ul>
        <h3 class="muted">appserver example</h3>
    </div>

    <hr>

    <div class="jumbotron">
        <a href="http://appserver.io">
            <img src="http://appserver.io/static/img/logo-black.png"/>
        </a>
        <h1>example</h1>
        <p class="lead">
            Succesfully passed authentication
        </p>
    </div>

    <hr>

    <div class="row-fluid marketing">

        <div class="span12 text-center">
            <?php if ($errorMessages = $this->getAttribute('errorMessages')): ?>
                <div class="alert alert-error">
                    <?php foreach ($errorMessages as $errorMessage): ?>
                        <?php echo $errorMessage ?></br>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>

    </div>

    <hr>

    <div class="footer">
        <p>&copy; appserver.io 2013</p>
    </div>

</div> <!-- /container -->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="components/require.js"></script>

</body>
</html>
