<?php

/**
 * templates\login.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

namespace TechDivision\Example\Servlets;

use TechDivision\Example\Utils\ContextKeys;

/** @var $this \TechDivision\Example\Servlets\LoginServlet */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <base href="<?php echo $this->getBaseUrl() ?>">
    <title>Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="components/require.css" rel="stylesheet">
    <link rel="shortcut icon" href="static/img/favicon.png">
    <style type="text/css">
        body {
            padding-top: 20px;
            padding-bottom: 40px;
        }

        /* Custom container */
        .container-narrow {
            margin: 0 auto;
            max-width: 700px;
        }

        .container-narrow > hr {
            margin: 30px 0;
        }

        /* Main marketing message and sign up button */
        .jumbotron {
            margin: 60px 0;
            text-align: center;
        }

        .jumbotron h1 {
            font-size: 72px;
            line-height: 1;
        }

        .jumbotron .btn {
            font-size: 21px;
            padding: 14px 24px;
        }

        /* Supporting marketing content */
        .marketing {
            margin: 60px 0;
        }

        .marketing p + h4 {
            margin-top: 28px;
        }

        .form-signin {
            max-width: 300px;
            padding: 19px 29px 29px;
            margin: 0 auto 20px;
            background-color: #fff;
            border: 1px solid #e5e5e5;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            box-shadow: 0 1px 2px rgba(0,0,0,.05);
        }
        .form-signin .form-signin-heading,
        .form-signin .checkbox {
            margin-bottom: 10px;
        }
        .form-signin input[type="text"],
        .form-signin input[type="password"] {
            font-size: 16px;
            height: auto;
            margin-bottom: 15px;
            padding: 7px 9px;
        }

    </style>

</head>

<body>

<div class="container-narrow">

    <div class="masthead">
        <ul class="nav nav-pills pull-right">
            <li><a href="index.do">Home</a></li>
            <li class="active"><a href="login.do">Login</a></li>
            <li><a href="upload.do">Upload</a></li>
            <li><a href="websocket.do">WebSocket</a></li>
            <li><a href="basicAuthentication.do">Basic Authentication</a></li>
            <li><a href="digestAuthentication.do">Digest Authentication</a></li>
            <li><a href="messageQueue.do">Message-Queue</a></li>
        </ul>
        <h3 class="muted">appserver example</h3>
    </div>

    <hr>

    <div class="row-fluid">
        <div class="span12">
            <p>
                <?php if ($this->getServletRequest()->getSession()->hasKey('username')) { ?>
                    Logged in as: <strong><?php echo $this->getServletRequest()->getSession()->getData('username') ?></strong>
                <?php } else { ?>
                    Not logged in.
                <?php } ?>
            </p>
            <?php if ($errorMessages = $this->getAttribute('errorMessages')) { ?>
                <div class="alert alert-error">
                <?php foreach ($errorMessages as $errorMessage) { ?>
                    <?php echo $errorMessage ?></br>
                <?php } ?>
                </div>
            <?php } ?>
        </div>
    </div>

    <form class="form-signin" action="login.do/login" method="post">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input name="username" type="text" class="input-block-level" placeholder="Username">
        <input name="password" type="password" class="input-block-level" placeholder="Password">
        <label class="checkbox">
            <input type="checkbox" value="remember-me"> Remember me
        </label>
        <button class="btn btn-large btn-primary" type="submit">Sign in</button>
    </form>

    <hr>

    <div class="footer">
        <p>&copy; appserver.io 2014</p>
    </div>

</div> <!-- /container -->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="components/require.js"></script>

</body>
</html>
