<?php

/**
 * templates\login.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

namespace TechDivision\Example\Servlets;

use TechDivision\Example\Utils\ContextKeys;

/** @var $this \TechDivision\Example\Servlets\LoginServlet */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <base href="<?php echo $this->getBaseUrl() ?>">
    <title>Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="components/require.css" rel="stylesheet">
    <link rel="shortcut icon" href="static/img/favicon.png">
    <style type="text/css">
        body {
            padding-top: 20px;
            padding-bottom: 40px;
        }

        /* Custom container */
        .container-narrow {
            margin: 0 auto;
            max-width: 700px;
        }

        .container-narrow > hr {
            margin: 30px 0;
        }

        /* Main marketing message and sign up button */
        .jumbotron {
            margin: 60px 0;
            text-align: center;
        }

        .jumbotron h1 {
            font-size: 72px;
            line-height: 1;
        }

        .jumbotron .btn {
            font-size: 21px;
            padding: 14px 24px;
        }

        /* Supporting marketing content */
        .marketing {
            margin: 60px 0;
        }

        .marketing p + h4 {
            margin-top: 28px;
        }

        .central {
            text-align: center;
        }

        .re-centered {
            margin-left: 35%;
        }
    </style>

</head>

<body>

<div class="container-narrow">

    <div class="masthead">
        <ul class="nav nav-pills pull-right">
            <li><a href="index.do">Home</a></li>
            <li><a href="login.do">Login</a></li>
            <li class="active"><a href="upload.do">Upload</a></li>
            <li><a href="websocket.do">WebSocket</a></li>
            <li><a href="basicAuthentication.do">Basic Authentication</a></li>
            <li><a href="digestAuthentication.do">Digest Authentication</a></li>
        </ul>
        <h3 class="muted">appserver example</h3>
    </div>

    <hr>

    <div class="row-fluid marketing central">
            <form class="form-upload" action="upload.do/upload" method="post" enctype="multipart/form-data">
                <h2 class="form-upload-heading">Select file</h2>
                <input name="fileToUpload" type="file" class="input-block-level re-centered" placeholder="Filename">
                <button class="btn btn-large btn-primary" type="submit">Upload file</button>
            </form>
    </div>

    <hr>

    <div class="footer">
        <p>&copy; appserver.io 2014</p>
    </div>

</div>
<!-- /container -->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="components/require.js"></script>

</body>
</html>
