<?php

/**
 * templates\login.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

namespace TechDivision\Example\Servlets;

use TechDivision\Example\Utils\ContextKeys;

/** @var $this \TechDivision\Example\Servlets\LoginServlet */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <base href="<?php echo $this->getBaseUrl() ?>">
    <title>Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="components/require.css" rel="stylesheet">
    <link rel="shortcut icon" href="static/img/favicon.png">
    <style type="text/css">
        body {
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            max-width: 300px;
            padding: 19px 29px 29px;
            margin: 0 auto 20px;
            background-color: #fff;
            border: 1px solid #e5e5e5;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            box-shadow: 0 1px 2px rgba(0,0,0,.05);
        }
        .form-signin .form-signin-heading,
        .form-signin .checkbox {
            margin-bottom: 10px;
        }
        .form-signin input[type="text"],
        .form-signin input[type="password"] {
            font-size: 16px;
            height: auto;
            margin-bottom: 15px;
            padding: 7px 9px;
        }

    </style>

</head>

<body>

<div class="container">

    <div class="masthead">
        <ul class="nav nav-pills pull-right">
            <li><a href="index/index">Home</a></li>
            <li><a href="login/index">Login</a></li>
            <li class="active"><a href="upload/index">Upload</a></li>
        </ul>
        <h3 class="muted">appserver example</h3>
    </div>

    <div class="row-fluid">
        <div class="span12">
            <?php if ($this->getRequest()->getSession()->hasKey('username')) { ?>
                <div>
                    <p><?php echo $this->getRequest()->getSession()->getData('username') ?></p>
                </div>
            <?php } ?>
            <?php if ($errorMessages = $this->getAttribute('errorMessages')) { ?>
                <div class="alert alert-error">
                <?php foreach ($errorMessages as $errorMessage) { ?>
                    <?php echo $errorMessage ?></br>
                <?php } ?>
                </div>
            <?php } ?>
        </div>
    </div>

    <form class="form-upload" action="upload/upload" method="post" enctype="multipart/form-data">
        <input type="hidden" name="action" value="upload" />
        <h2 class="form-upload-heading">Select file</h2>
        <input name="fileToUpload" type="file" class="input-block-level" placeholder="Filename">
        <button class="btn btn-large btn-primary" type="submit">Upload file</button>
    </form>

    <hr>

    <div class="footer">
        <p>&copy; appserver.io 2013</p>
    </div>

</div> <!-- /container -->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="components/require.js"></script>

</body>
</html>
