<?php

/**
 * templates\websocket.phtml
*
* NOTICE OF LICENSE
*
* This source file is subject to the Open Software License (OSL 3.0)
* that is available through the world-wide-web at this URL:
* http://opensource.org/licenses/osl-3.0.php
*/

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <base href="<?php echo $this->getBaseUrl() ?>">
    <title>Example</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="components/require.css" rel="stylesheet">
    <link rel="shortcut icon" href="static/img/favicon.png">
    <style type="text/css">
        body {
            padding-top: 20px;
            padding-bottom: 40px;
        }

            /* Custom container */
        .container-narrow {
            margin: 0 auto;
            max-width: 700px;
        }
        .container-narrow > hr {
            margin: 30px 0;
        }

            /* Main marketing message and sign up button */
        .jumbotron {
            margin: 60px 0;
            text-align: center;
        }
        .jumbotron h1 {
            font-size: 72px;
            line-height: 1;
        }
        .jumbotron .btn {
            font-size: 21px;
            padding: 14px 24px;
        }

            /* Supporting marketing content */
        .marketing {
            margin: 60px 0;
        }
        .marketing p + h4 {
            margin-top: 28px;
        }
    </style>
</head>

<body>

<div class="container-narrow">

    <div class="masthead">
        <ul class="nav nav-pills pull-right">
            <li><a href="index/index">Home</a></li>
            <li><a href="login/index">Login</a></li>
            <li><a href="upload/index">Upload</a></li>
            <li class="active"><a href="websocket/index">WebSocket</a></li>
            <li><a href="basicAuthentication/index">Basic Authentication</a></li>
            <li><a href="digestAuthentication/index">Digest Authentication</a></li>
        </ul>
        <h3 class="muted">appserver example</h3>
    </div>

    <hr>

    <div class="jumbotron">
        <a href="http://appserver.io">
            <img src="http://appserver.io/static/img/logo-black.png"/>
        </a>
        <h1>websocket example</h1>
    </div>

    <hr>

    <div class="row-fluid marketing">

        <div class="span12 text-center">
            <form id="personForm" class="form-inline" action="index" method="post">
                <input type="hidden" name="action" value="persist" />
                <input type="hidden" name="sampleId" />
                <input name="name" type="text" placeholder="Type your name..." />
                <button type="submit" class="btn">Submit</button>
            </form>
        </div>

        <div class="span12">
            <table id="results" class="table table-hover">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody/>
            </table>
        </div>
    </div>

    <hr>

    <div class="footer">
        <p>&copy; appserver.io 2014</p>
    </div>

</div> <!-- /container -->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="components/require.js"></script>
<script type="text/javascript">

    var connSample = new WebSocket('ws://127.0.0.1:8589/example/sample');

    connSample.onopen = function(e) {
        console.log("Connection to sample handler established!");
	    connSample.send('action=overview');
    };

    var connUser = new WebSocket('ws://127.0.0.1:8589/example/user');

    connUser.onopen = function(e) {
        console.log("Connection to user handler established!");
    };

    connSample.onmessage = function(e) {
        console.log("Sample-Handler: " + e.data);
        require(['jquery'], function($) {
        	var data = JSON.parse(e.data);
        	for (i = 0; i < data.length; i++) {
        	    $('#results > tbody:last').append('<tr><td>'+ data[i].sampleId +'</td><td>'+ data[i].name +'</td><td>Edit</td></tr>');
        	}
		});
    };

    connUser.onmessage = function(e) {
        console.log("User-Handler: " + e.data);
    };

    require(['jquery'], function($) {
    	$("#personForm").submit(function(event) {
        	var serializedValues = $(this).serialize();
    	    console.log(serializedValues);
    	    connSample.send(serializedValues);
    	    event.preventDefault();
		});
    });

</script>
</body>
</html>