<?php

/**
 * templates\index.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

namespace TechDivision\Example\Servlets;

use TechDivision\Example\Utils\ContextKeys;

// load the entity data if available
if ($entity = $this->getAttribute(ContextKeys::VIEW_DATA)) {
    $sampleId = $entity->getSampleId();
    $name = $entity->getName();
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <base href="<?php echo $this->getBaseUrl() ?>">
    <title>Example</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="components/require.css" rel="stylesheet">
    <style type="text/css">
        body {
            padding-top: 20px;
            padding-bottom: 40px;
        }

            /* Custom container */
        .container-narrow {
            margin: 0 auto;
            max-width: 700px;
        }
        .container-narrow > hr {
            margin: 30px 0;
        }

            /* Main marketing message and sign up button */
        .jumbotron {
            margin: 60px 0;
            text-align: center;
        }
        .jumbotron h1 {
            font-size: 72px;
            line-height: 1;
        }
        .jumbotron .btn {
            font-size: 21px;
            padding: 14px 24px;
        }

            /* Supporting marketing content */
        .marketing {
            margin: 60px 0;
        }
        .marketing p + h4 {
            margin-top: 28px;
        }
    </style>
</head>

<body>

<div class="container-narrow">

    <div class="masthead">
        <ul class="nav nav-pills pull-right">
            <li class="active"><a href="index/index">Home</a></li>
            <li><a href="login/index">Login</a></li>
        </ul>
        <h3 class="muted">appserver example</h3>
    </div>

    <hr>

    <div class="jumbotron">
        <a href="http://appserver.io">
            <img src="http://appserver.io/static/img/logo-black.png"/>
        </a>
        <h2>example</h2>
        <?php if ($this->getRequest()->getSession()->hasKey('username')) { ?>
            <p class="lead">
                Logged in as: <strong><?php echo $this->getRequest()->getSession()->getData('username') ?></strong>
            </p>
        <?php } ?>
    </div>

    <hr>

    <div class="row-fluid marketing">

        <div class="span12 text-center">
            <?php if ($errorMessages = $this->getAttribute('errorMessages')) { ?>
                <div class="alert alert-error">
                    <?php foreach ($errorMessages as $errorMessage) { ?>
                        <?php echo $errorMessage ?></br>
                    <?php } ?>
                </div>
            <?php } ?>

            <form class="form-inline" action="index" method="post">
                <input type="hidden" name="action" value="persist" />
                <input type="hidden" name="sampleId" value="<?php echo $sampleId ?>">
                <input name="name" type="text" placeholder="Type your name..." value="<?php echo $name ?>">
                <button type="submit" class="btn">Submit</button>
            </form>
        </div>

        <div class="span12">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody><?php foreach ($this->getAttribute(ContextKeys::OVERVIEW_DATA) as $entity) { ?>
                <tr>
                    <td><a href="<?php echo $this->getEditLink($entity) ?>"><?php echo $entity->getSampleId() ?></a></td>
                    <td><?php echo $entity->getName() ?></td>
                    <td><a href="<?php echo $this->getDeleteLink($entity) ?>">Delete</a></td><?php } ?>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <hr>

    <div class="footer">
        <p>&copy; appserver.io 2013</p>
    </div>

</div> <!-- /container -->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="components/require.js"></script>

</body>
</html>
