<?php

/**
 * templates\login.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

namespace TechDivision\Example\Servlets;

use TechDivision\Example\Utils\ContextKeys;

?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <base href="/example/">
    </head>
    <body>
    <div>
        <ul>
            <li><a href="index">Home</a></li>
            <li><a href="login/index">Login</a></li>
        </ul>
    </div>
    <div>
        <img src="static/images/logo.jpg"/>
    </div>
    <?php if ($req->getSession()->hasKey('username')) { ?><div>
        <p><?php echo $req->getSession()->getData('username') ?></p>
    <?php } ?></div>
    <?php if ($errorMessages = $this->getAttribute('errorMessages')) { ?><ul>
        <?php foreach ($errorMessages as $errorMessage) { ?><li>
            <?php echo $errorMessage ?>
        </li><?php } ?>
    </ul><?php } ?>
    <div>
        <form action="login/login" method="get">
            <input type="hidden" name="action" value="login" />
            <fieldset>
                <legend>Sample</legend>
                <table>
                    <tr>
                        <td>Id:</td>
                        <td><input type="text" size="40" maxlength="40" name="username" value=""></td>
                    </tr>
                    <tr>
                        <td>Name:</td>
                        <td><input type="password" size="40" maxlength="40" name="password" value=""></td>
                    </tr>
                    <tr>
                        <td colspan="2"><input type="submit" value="Login"/></td>
                    </tr>
                </table>
            </fieldset>
        </form>
    </div>
    </body>
</html>